// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace MvvmTest.iOS
{
	public partial class MvvmTest_iOSViewController : UIViewController
	{
		public MvvmTest_iOSViewController (IntPtr handle) : base (handle)
		{

		}
	}
}
