// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MvvmTest.Core._02;
using Praeclarum.Bind;

namespace MvvmTest.iOS
{
	public partial class ViewModelDrivenController : UIViewController
	{
		private readonly LoginViewModel _viewModel;

		public ViewModelDrivenController (IntPtr handle) : base (handle)
		{
			_viewModel = new LoginViewModel();
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			_login.TouchUpInside += (sender, e) => _viewModel.Login();

			Binding.Create(() => _username.Text == _viewModel.UserName);
			Binding.Create(() => _password.Text == _viewModel.Password);

			Binding.Error += message =>
			{
				Console.WriteLine(message);
			};
		}
	}
}
